### ISSUE TITLE
小心点吧

### ISSUE THREAD

**Issue by emstt** [HSAllenbili/bye_pft#1]
![图片](https://github.com/HSAllenbili/bye_pft/assets/153365219/3689acc0-2747-4833-8db9-8ec819945358)
开始整改了 不避避风头？

**Comment by HSAllenbili** [comment]
估计整改的越权漏洞，没多大事

**Comment by emstt** [comment]
你的deletererordId api是解包小程序拿的吧 这还不够越权？

**Comment by HSAllenbili** [comment]
deleterecord是小程序之前的版本留下来的接口 用于自动删除无效记录的 本来就是开放给用户的

**Comment by emstt** [comment]
ao 原来如此
